# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\CMake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\CMake\bin\cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "Z:\Projects\Minecraft Seed Renderer"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "Z:\Projects\Minecraft Seed Renderer"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	"C:\Program Files\CMake\bin\cmake-gui.exe" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	"C:\Program Files\CMake\bin\cmake.exe" --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	"C:\Program Files\CMake\bin\cmake.exe" -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	"C:\Program Files\CMake\bin\cmake.exe" -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	"C:\Program Files\CMake\bin\cmake.exe" -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	"C:\Program Files\CMake\bin\cmake.exe" -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	"C:\Program Files\CMake\bin\cmake.exe" -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	"C:\Program Files\CMake\bin\cmake.exe" -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "Z:\Projects\Minecraft Seed Renderer\CMakeFiles" "Z:\Projects\Minecraft Seed Renderer\\CMakeFiles\progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "Z:\Projects\Minecraft Seed Renderer\CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named mc_seed_renderer

# Build rule for target.
mc_seed_renderer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 mc_seed_renderer
.PHONY : mc_seed_renderer

# fast build rule for target.
mc_seed_renderer/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\mc_seed_renderer.dir\build.make CMakeFiles/mc_seed_renderer.dir/build
.PHONY : mc_seed_renderer/fast

#=============================================================================
# Target rules for targets named run_test

# Build rule for target.
run_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 run_test
.PHONY : run_test

# fast build rule for target.
run_test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\run_test.dir\build.make CMakeFiles/run_test.dir/build
.PHONY : run_test/fast

#=============================================================================
# Target rules for targets named spng

# Build rule for target.
spng: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 spng
.PHONY : spng

# fast build rule for target.
spng/fast:
	$(MAKE) $(MAKESILENT) -f _deps\libspng-build\CMakeFiles\spng.dir\build.make _deps/libspng-build/CMakeFiles/spng.dir/build
.PHONY : spng/fast

#=============================================================================
# Target rules for targets named example

# Build rule for target.
example: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 example
.PHONY : example

# fast build rule for target.
example/fast:
	$(MAKE) $(MAKESILENT) -f _deps\libspng-build\CMakeFiles\example.dir\build.make _deps/libspng-build/CMakeFiles/example.dir/build
.PHONY : example/fast

#=============================================================================
# Target rules for targets named spng_static

# Build rule for target.
spng_static: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 spng_static
.PHONY : spng_static

# fast build rule for target.
spng_static/fast:
	$(MAKE) $(MAKESILENT) -f _deps\libspng-build\CMakeFiles\spng_static.dir\build.make _deps/libspng-build/CMakeFiles/spng_static.dir/build
.PHONY : spng_static/fast

#=============================================================================
# Target rules for targets named libcubiomes

# Build rule for target.
libcubiomes: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 libcubiomes
.PHONY : libcubiomes

# fast build rule for target.
libcubiomes/fast:
	$(MAKE) $(MAKESILENT) -f lib\libcubiomes\CMakeFiles\libcubiomes.dir\build.make lib/libcubiomes/CMakeFiles/libcubiomes.dir/build
.PHONY : libcubiomes/fast

_deps/libspng-src/spng/spng.obj: _deps/libspng-src/spng/spng.c.obj
.PHONY : _deps/libspng-src/spng/spng.obj

# target to build an object file
_deps/libspng-src/spng/spng.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\mc_seed_renderer.dir\build.make CMakeFiles/mc_seed_renderer.dir/_deps/libspng-src/spng/spng.c.obj
.PHONY : _deps/libspng-src/spng/spng.c.obj

_deps/libspng-src/spng/spng.i: _deps/libspng-src/spng/spng.c.i
.PHONY : _deps/libspng-src/spng/spng.i

# target to preprocess a source file
_deps/libspng-src/spng/spng.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\mc_seed_renderer.dir\build.make CMakeFiles/mc_seed_renderer.dir/_deps/libspng-src/spng/spng.c.i
.PHONY : _deps/libspng-src/spng/spng.c.i

_deps/libspng-src/spng/spng.s: _deps/libspng-src/spng/spng.c.s
.PHONY : _deps/libspng-src/spng/spng.s

# target to generate assembly for a file
_deps/libspng-src/spng/spng.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\mc_seed_renderer.dir\build.make CMakeFiles/mc_seed_renderer.dir/_deps/libspng-src/spng/spng.c.s
.PHONY : _deps/libspng-src/spng/spng.c.s

lib/olive.c/olive.obj: lib/olive.c/olive.c.obj
.PHONY : lib/olive.c/olive.obj

# target to build an object file
lib/olive.c/olive.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\mc_seed_renderer.dir\build.make CMakeFiles/mc_seed_renderer.dir/lib/olive.c/olive.c.obj
.PHONY : lib/olive.c/olive.c.obj

lib/olive.c/olive.i: lib/olive.c/olive.c.i
.PHONY : lib/olive.c/olive.i

# target to preprocess a source file
lib/olive.c/olive.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\mc_seed_renderer.dir\build.make CMakeFiles/mc_seed_renderer.dir/lib/olive.c/olive.c.i
.PHONY : lib/olive.c/olive.c.i

lib/olive.c/olive.s: lib/olive.c/olive.c.s
.PHONY : lib/olive.c/olive.s

# target to generate assembly for a file
lib/olive.c/olive.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\mc_seed_renderer.dir\build.make CMakeFiles/mc_seed_renderer.dir/lib/olive.c/olive.c.s
.PHONY : lib/olive.c/olive.c.s

src/args.obj: src/args.c.obj
.PHONY : src/args.obj

# target to build an object file
src/args.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\mc_seed_renderer.dir\build.make CMakeFiles/mc_seed_renderer.dir/src/args.c.obj
.PHONY : src/args.c.obj

src/args.i: src/args.c.i
.PHONY : src/args.i

# target to preprocess a source file
src/args.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\mc_seed_renderer.dir\build.make CMakeFiles/mc_seed_renderer.dir/src/args.c.i
.PHONY : src/args.c.i

src/args.s: src/args.c.s
.PHONY : src/args.s

# target to generate assembly for a file
src/args.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\mc_seed_renderer.dir\build.make CMakeFiles/mc_seed_renderer.dir/src/args.c.s
.PHONY : src/args.c.s

src/color.obj: src/color.c.obj
.PHONY : src/color.obj

# target to build an object file
src/color.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\mc_seed_renderer.dir\build.make CMakeFiles/mc_seed_renderer.dir/src/color.c.obj
.PHONY : src/color.c.obj

src/color.i: src/color.c.i
.PHONY : src/color.i

# target to preprocess a source file
src/color.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\mc_seed_renderer.dir\build.make CMakeFiles/mc_seed_renderer.dir/src/color.c.i
.PHONY : src/color.c.i

src/color.s: src/color.c.s
.PHONY : src/color.s

# target to generate assembly for a file
src/color.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\mc_seed_renderer.dir\build.make CMakeFiles/mc_seed_renderer.dir/src/color.c.s
.PHONY : src/color.c.s

src/dynamicarray.obj: src/dynamicarray.c.obj
.PHONY : src/dynamicarray.obj

# target to build an object file
src/dynamicarray.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\mc_seed_renderer.dir\build.make CMakeFiles/mc_seed_renderer.dir/src/dynamicarray.c.obj
.PHONY : src/dynamicarray.c.obj

src/dynamicarray.i: src/dynamicarray.c.i
.PHONY : src/dynamicarray.i

# target to preprocess a source file
src/dynamicarray.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\mc_seed_renderer.dir\build.make CMakeFiles/mc_seed_renderer.dir/src/dynamicarray.c.i
.PHONY : src/dynamicarray.c.i

src/dynamicarray.s: src/dynamicarray.c.s
.PHONY : src/dynamicarray.s

# target to generate assembly for a file
src/dynamicarray.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\mc_seed_renderer.dir\build.make CMakeFiles/mc_seed_renderer.dir/src/dynamicarray.c.s
.PHONY : src/dynamicarray.c.s

src/img_gen_test.obj: src/img_gen_test.c.obj
.PHONY : src/img_gen_test.obj

# target to build an object file
src/img_gen_test.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\mc_seed_renderer.dir\build.make CMakeFiles/mc_seed_renderer.dir/src/img_gen_test.c.obj
.PHONY : src/img_gen_test.c.obj

src/img_gen_test.i: src/img_gen_test.c.i
.PHONY : src/img_gen_test.i

# target to preprocess a source file
src/img_gen_test.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\mc_seed_renderer.dir\build.make CMakeFiles/mc_seed_renderer.dir/src/img_gen_test.c.i
.PHONY : src/img_gen_test.c.i

src/img_gen_test.s: src/img_gen_test.c.s
.PHONY : src/img_gen_test.s

# target to generate assembly for a file
src/img_gen_test.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\mc_seed_renderer.dir\build.make CMakeFiles/mc_seed_renderer.dir/src/img_gen_test.c.s
.PHONY : src/img_gen_test.c.s

src/libattopng.obj: src/libattopng.c.obj
.PHONY : src/libattopng.obj

# target to build an object file
src/libattopng.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\mc_seed_renderer.dir\build.make CMakeFiles/mc_seed_renderer.dir/src/libattopng.c.obj
.PHONY : src/libattopng.c.obj

src/libattopng.i: src/libattopng.c.i
.PHONY : src/libattopng.i

# target to preprocess a source file
src/libattopng.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\mc_seed_renderer.dir\build.make CMakeFiles/mc_seed_renderer.dir/src/libattopng.c.i
.PHONY : src/libattopng.c.i

src/libattopng.s: src/libattopng.c.s
.PHONY : src/libattopng.s

# target to generate assembly for a file
src/libattopng.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\mc_seed_renderer.dir\build.make CMakeFiles/mc_seed_renderer.dir/src/libattopng.c.s
.PHONY : src/libattopng.c.s

src/main.obj: src/main.c.obj
.PHONY : src/main.obj

# target to build an object file
src/main.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\mc_seed_renderer.dir\build.make CMakeFiles/mc_seed_renderer.dir/src/main.c.obj
.PHONY : src/main.c.obj

src/main.i: src/main.c.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\mc_seed_renderer.dir\build.make CMakeFiles/mc_seed_renderer.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\mc_seed_renderer.dir\build.make CMakeFiles/mc_seed_renderer.dir/src/main.c.s
.PHONY : src/main.c.s

src/util.obj: src/util.c.obj
.PHONY : src/util.obj

# target to build an object file
src/util.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\mc_seed_renderer.dir\build.make CMakeFiles/mc_seed_renderer.dir/src/util.c.obj
.PHONY : src/util.c.obj

src/util.i: src/util.c.i
.PHONY : src/util.i

# target to preprocess a source file
src/util.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\mc_seed_renderer.dir\build.make CMakeFiles/mc_seed_renderer.dir/src/util.c.i
.PHONY : src/util.c.i

src/util.s: src/util.c.s
.PHONY : src/util.s

# target to generate assembly for a file
src/util.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\mc_seed_renderer.dir\build.make CMakeFiles/mc_seed_renderer.dir/src/util.c.s
.PHONY : src/util.c.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... install
	@echo ... install/local
	@echo ... install/strip
	@echo ... list_install_components
	@echo ... rebuild_cache
	@echo ... run_test
	@echo ... example
	@echo ... libcubiomes
	@echo ... mc_seed_renderer
	@echo ... spng
	@echo ... spng_static
	@echo ... _deps/libspng-src/spng/spng.obj
	@echo ... _deps/libspng-src/spng/spng.i
	@echo ... _deps/libspng-src/spng/spng.s
	@echo ... lib/olive.c/olive.obj
	@echo ... lib/olive.c/olive.i
	@echo ... lib/olive.c/olive.s
	@echo ... src/args.obj
	@echo ... src/args.i
	@echo ... src/args.s
	@echo ... src/color.obj
	@echo ... src/color.i
	@echo ... src/color.s
	@echo ... src/dynamicarray.obj
	@echo ... src/dynamicarray.i
	@echo ... src/dynamicarray.s
	@echo ... src/img_gen_test.obj
	@echo ... src/img_gen_test.i
	@echo ... src/img_gen_test.s
	@echo ... src/libattopng.obj
	@echo ... src/libattopng.i
	@echo ... src/libattopng.s
	@echo ... src/main.obj
	@echo ... src/main.i
	@echo ... src/main.s
	@echo ... src/util.obj
	@echo ... src/util.i
	@echo ... src/util.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

